require_relative 'manticore/jars/httpcore-4.4.1.jar'
require_relative 'manticore/jars/commons-codec-1.10.jar'
require_relative 'manticore/jars/commons-logging-1.2.jar'
require_relative 'manticore/jars/httpmime-4.5.2.jar'
require_relative 'manticore/jars/httpclient-4.5.2.jar'
