name: JRuby CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jruby: 'jruby-head', jdk: '21', experimental: true }
          - { jruby: 'jruby-9.4.12.0', jdk: '21', jruby_opts: '-Xcompile.invokedynamic -Xjit.threshold=0' }
          - { jruby: 'jruby-9.4.12.0', jdk: '21' }
          - { jruby: 'jruby-9.4.12.0', jdk: '17' }
          - { jruby: 'jruby-9.3.15.0', jdk: '11' }
          - { jruby: 'jruby-9.3.15.0', jdk: '21' }

    continue-on-error: ${{ matrix.experimental || false }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.distro || 'temurin' }}

      - name: Set up JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.jruby }}
          bundler-cache: true

      - name: Install specific Bundler version
        run: gem install bundler -v '~> 2'

      - name: Run tests
        env:
          JRUBY_OPTS: ${{ matrix.jruby_opts || '' }}
        run: |
          bundle install
          bundle exec rake

