name: JRuby CI

on: [push, pull_request]

env:
  JRUBY_OPTS: '-J-ea -J-Djruby.ji.ambiguous.calls.debug=true'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jruby: 'jruby-10.0.0.1', jdk: '21' }
          - { jruby: 'jruby-9.4.12.0', jdk: '21', jruby_opts: '-Xcompile.invokedynamic -Xjit.threshold=0' }
          - { jruby: 'jruby-9.4.13.0', jdk: '21' }
          - { jruby: 'jruby-9.4.13.0', jdk: '17' }
          - { jruby: 'jruby-9.4.13.0', jdk: '11' }
          - { jruby: 'jruby-9.3.15.0', jdk: '11' }
          - { jruby: 'jruby-9.3.15.0', jdk:  '8' }

    continue-on-error: ${{ matrix.experimental || false }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.distro || 'temurin' }}

      - name: Set up JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.jruby }}
          bundler-cache: true

      - name: Bundle install
        run: |
          bundle install

      - name: Run tests
        run: |
          jruby -rbundler/setup -S rake generate_certs
          echo "JRUBY_OPTS=${JRUBY_OPTS} ${{ matrix.jruby_opts || '' }}" >> $GITHUB_ENV
          jruby -rbundler/setup -S rake spec
